---
author: "Sokona Mangane"
title: "HW 3: Random Number STreams"
output: html_document
date: "2023-02-01"
---

# DCS 307 - HW 3

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r package setup}
library(simEd)
```



```{r pressure, echo=FALSE}

myArr1 <- function() {rexp(1, rate = 1)}
myArr2 <- function() {rexp(1, rate = 11/10)}
mySvc1 <- function() {rexp(1, rate = 10/9)}

#using first arrival rate
output1 <- ssq(maxArrivals = 20, seed = 8675309, interarrivalFcn = myArr1(), serviceFcn = mySvc1(), saveAllStats = TRUE, showOutput =  FALSE)

#using second arrival rate, yet the same service function
output2 <- ssq(maxArrivals = 20, seed = 8675309, interarrivalFcn = myArr2(), serviceFcn = mySvc1(), saveAllStats = TRUE, showOutput =  FALSE)


interarrival1 <- output1$interarrivalTimes
service1 <- output1$serviceTimes

interarrival2 <- output2$interarrivalTimes
service2 <- output2$serviceTimes

```

## Question 1: What are the first ten service times from the first run?


## Question 2: What are the first ten service times from the second run?


