output:
author:
title: 
Date:



```{r setup}

#install.packages("simEd")
library(simEd)
```
The `rep()` repicates values in x. See examples below.

```{r}
rep(1:4, 3) #repeats the list (1st argument)3 times

example("rep") #prints all the examples from the help documenation of ?rep

seq(1,10, by = 1) #prints out a sequene of numbers by the increment given (2nd argument)
```


```{r}
sample(1:6,1) #can use this to roll a single die 
```


```{r}
#can use the #quantiles() function to return the 25% 50% 75% etc quantiles in a list

#quantiles(list, prob = c(0.33, 0.5, 0.67, 0.95)), gives us quantiles but at different percentages: 33%, 50%, 67% & 95%
```


```{r}
#we can use the abline() function to draw a line on a histogram, plot, etc

# oneHistogram <- function(num_rolls = 1000)
# {
#   all_estimates <- getEstimates(1000, num_rolls)
#   hist(all_estimates, xlim = c(0.05, 0.3))
#   m <- mean(all_estimates)
#   abline(v = m, col = "blue", lwd = 2)
#   s <- sd(all_estimates)
#   abline(v = c(m - 2*s, m + 2*s), col = "red", lwd = 2, lty = "dashed") 
# }
# 
# 
# #par(mfrow = c(1,3)) # display 1 row, 3 columns
# par(mfrow = c(3,1)) # display 3 rows, 1 column
# 
# oneHistogram(100)
# oneHistogram(500)
# oneHistogram(1000) 
```


Stopped video at 59:45
